from tests.entities.TestValidators import *
from tests.entities.TestCliente import *
from tests.entities.TestCategoria import *
from tests.entities.TestCobrancaFactory import *
from tests.entities.TestTypeCpf import *
from tests.utils.TestUtilsPedido import *
from tests.db.django_orm.TestClienteDaoOrm import *
from tests.entities.TestPedidoFactory import *
from tests.entities.TestPedido import *
from tests.entities.TestProdutoFactory import *
from tests.external.TestCatalogoWsImpl import *
from tests.db.django_orm.TestPedidoRepositoryOrm import *
from tests.usecases.TestUseCasePedido import *
from tests.web.django_views.TestClientView import *
from tests.web.django_views.TestClientDetalhesView import *
from tests.web.django_views.TestPedidoView import *
from tests.web.django_views.TestCriarUsuarioView import *
