# Generated by Django 4.2.1 on 2024-03-13 23:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('nome', models.CharField(help_text='Informe o nome do cliente, evite o uso de caracteres especiais.', max_length=120, verbose_name='Nome completo do cliente')),
                ('email', models.CharField(max_length=120, unique=True)),
                ('cpf', models.CharField(max_length=11, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('nome', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('valor', models.FloatField()),
                ('status', models.CharField(choices=[('aguardando_pagamento', 'aguardando_pagamento'), ('preparando', 'preparando'), ('pronto', 'pronto'), ('recebido', 'recebido'), ('finalizado', 'finalizado'), ('cancelado', 'cancelado')], default='aguardando_pagamento', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=1024, null=True)),
                ('preco', models.FloatField()),
                ('imagem_url', models.CharField(max_length=1024, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('descricao', models.CharField(blank=True, max_length=1024, null=True)),
                ('preco', models.FloatField()),
                ('imagem_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('categoria', models.CharField(blank=True, max_length=40, null=True)),
                ('quantidade', models.PositiveIntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4)),
                ('valor', models.FloatField()),
                ('status', models.CharField(choices=[('pendente', 'pendente'), ('cancelado', 'cancelado'), ('recebido', 'recebido')], default='pendente', max_length=40)),
                ('fornecedor_meio_pagto', models.CharField(default='mercadopago', max_length=40)),
                ('pix_codigo', models.CharField(blank=True, max_length=300, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pedido')),
            ],
        ),
    ]
